Repository cisco-ie/pipeline-gnmi, pull requests merged in 2019-05, with the labels that each got.

#16 Build Fixes
  .gitignore
  Makefile
  codec.go
  codec_gpb.go
  codec_gpb_test.go
  encap_st_test.go
  mdt_msg_samples/samples.go
  message_router_test.go
  metamonitoring.go
  metrics.go
  metrics_influx.go
  metrics_prometheus.go
  pipeline.go
  pipeline_test.go
  tap_test.go
  xport_gnmi.go
  xport_grpc.go
  xport_grpc_out.go
  xport_grpc_out_test.go
  xport_grpc_test.go
  xport_kafka.go
  xport_tcp_test.go
  xport_udp.go
  xport_udp_test.go
Labels: bug

#18 Test Fixes
  .gitignore
  Makefile
  skeleton/pipeline.mk
  xport_kafka_test.go
Labels: enhancement

#26 Set Kafka to only run for integration test
  xport_kafka_test.go
Labels: bug

#32 Go Report Card
  Makefile
  README.md
  skeleton/pipeline.mk
Labels: enhancement

#34 Remove Go module files
  go.mod
  go.sum
Labels: bug

#51 Prettify README
  README.md
Labels: documentation, enhancement

#52 Build MacOS, Linux, and Windows
  README.md
  skeleton/pipeline.mk
Labels: enhancement, ergonomics

#53 Cache Go modules
  .travis.yml
Labels: ergonomics, refactor, test
